server:
  port: 8100
spring:
  application:
    name: oauth2-server
  datasource:
    url: jdbc:mysql://${properties.mysql-addr}:${properties.mysql-port}/${properties.mysql-database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${properties.mysql-user}
    password: ${properties.mysql-pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
